[phases.setup]
nixPkgs = ["python312", "postgresql", "gcc", "cairo", "pkg-config", "pango", "gdk-pixbuf", "glib"]

[phases.install]
cmds = ["python3 -m venv /app/venv", "/app/venv/bin/pip install --upgrade pip", "/app/venv/bin/pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["cd backend && /app/venv/bin/python manage.py collectstatic --noinput"]


