[deploy]
startCommand = "echo 'Starting deployment...' && echo 'Database URL:' $DATABASE_URL && python manage.py migrate && echo 'Migration done, starting Gunicorn...' && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
