[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python3 manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
